### ISSUE TITLE
能支持自定义容器节点吗

### ISSUE THREAD

**Issue by CoderSerio** [oh-my-live2d/oh-my-live2d#18]
目前看上去好像只能挂载到body下面，但是需求是想在指定的位置展示——也就是希望能随着滚动条的滚动而移动

**Comment by loclink** [comment]
目前并不支持自定义模型容器，但在我未来的开发计划中其实包含此功能，奈何我一直忙于工作没有多余时间来维护这个库，若你有更多想法或者愿意的话，可以为此贡献代码，感谢支持🙏

**Comment by CoderSerio** [comment]
好的，
上面提到的需求，最后是通过加入了一个 index.html 引入 live2d，然后在 next 中使用 react-iframe 嵌入这个html页面实现的....
这样做总感觉有点别扭...
如果过一段时间（大概十月的时候，最近确实太忙了）还没有pr的话，我想我会来试试看。

**Comment by CoderSerio** [comment]
已PR: #20
