### ISSUE TITLE
请问支持Rspress吗

### ISSUE THREAD

**Issue by aojunhao123** [oh-my-live2d/oh-my-live2d#36]

**Comment by KISGP** [comment]
@aojunhao123 https://github.com/linbudu599/rspress-plugins/blob/main/packages/rspress-plugin-live2d/README.zh-CN.md

**Comment by aojunhao123** [comment]
> @aojunhao123 https://github.com/linbudu599/rspress-plugins/blob/main/packages/rspress-plugin-live2d/README.zh-CN.md

十分感谢！
