### ISSUE TITLE
如何关闭welcomeTips

### ISSUE THREAD

**Issue by kisssssssss** [oh-my-live2d/oh-my-live2d#38]
我在文档中并没有看到关于welcomeTips如何关闭的说明。能否实现当我传入 welcomeTips:null 的时候不显示欢迎信息
![image](https://github.com/oh-my-live2d/oh-my-live2d/assets/88269600/2c0744f0-33b3-4a0d-b80b-8bf58a78a358)

**Comment by hacxy** [comment]
暂时没有关闭的选项, 但是你可以给welcomeTips.message传一个空对象, 这样也可以实现关闭效果

**Comment by kisssssssss** [comment]
感谢

**Comment by tymon42** [comment]
刚刚试了下，好像不生效
```
      tips: {
        copyTips: {},
        idleTips: {},
        welcomeTips: {
          message: {},
        },
      },
      ```
      
      有具体的设置示例吗？
