### ISSUE TITLE
请问仓主后续会更新motion以及待机idle功能么？

### ISSUE THREAD

**Issue by LngYan** [oh-my-live2d/oh-my-live2d#9]

**Comment by loclink** [comment]
motion默认已加载了全部资源，模型的motion名称需要以 `tap_  || Tap` 作为前缀拼接上区域id即可，之后点击区域就可以触发对应的动作，以model3.json的配置文件为例：

![image](https://user-images.githubusercontent.com/106688231/216923133-7c45d29a-8d08-45cf-8600-8f1479484cc6.png)

名称需一一对应，且必须以`Tap || tap_` 开头。

至于 `idle` 待机功能，默认是会加载待机动画的。不知道您还需要哪些操作，可以说的具体点吗？

**Comment by LngYan** [comment]
我的模型文件感觉和仓主的不太一样motion文件夹就只有一个idle动画（并未自动开始），脸部动画都放在了expressions文件夹中，请问是不是需要模型目录结构是一致的才可以正常运行呢？
![12APJT) 6{_ 76`J~0VY_05](https://user-images.githubusercontent.com/123072945/217014820-58ef531e-d9ea-4c81-988c-934701c8c738.png)
![NJ8TQB8E{6M 24ZTQ@A__SH](https://user-images.githubusercontent.com/123072945/217015784-2eff1480-8d12-4056-aeb3-59b22c215040.png)

**Comment by loclink** [comment]
网络上大部分模型都没有对动作文件进行关联配置，有关模型的配置请使用相关工具，这里推荐使用Live2dViewerEX，它可以帮你找到每个区域的id和动作配置文件，以及更多可视化的配置操作。
![image](https://user-images.githubusercontent.com/106688231/217316965-e12f2c82-d83f-431b-b6f2-beaf4985df45.png)
